name: CI
on:
  pull_request:
    paths-ignore:
      - "doc/**"
      - README.md
  push:
    branches:
      - main

jobs:
  tests:
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          macos-latest,
          windows-latest,
        ]
        python-version: [
          '3.8',
          '3.10',
        ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup package
      # restricting to pip<22.0 because of pyvo
      # see https://github.com/astropy/pyvo/issues/296
      run:   |
        if [ "$RUNNER_OS" == "Linux" ]; then
            python -m pip install --upgrade pip\<22.0
        elif [ "$RUNNER_OS" == "Windows" ]; then
              python -m pip install --upgrade pip<22.0
        elif [ "$RUNNER_OS" == "macOS" ]; then
              python -m pip install --upgrade pip\<22.0
        fi
        python -m pip install .[dev]
    - name: Run tests
      run: |
        pytest
